### ISSUE TITLE
Create form component

### ISSUE THREAD

**Issue by shreshthagarwal** [EduMinerva/EduWeb#13]
Create a form component that inputs student details that are required for students registration

The event registration link must route to this component

### Instructions

1. Fork this repository
2. Clone your forked repository locally
3. Create the form component and route this component appropriately
4. Commit and push the changes
5. Create a pull request

**Comment by Rishi-0007** [comment]
assign this to me

**Comment by shreshthagarwal** [comment]
Sure, @Rishi-0007 you have been assigned this issue
